### ISSUE TITLE
Record label data?

### ISSUE THREAD

**Issue by nicolasespinoza** [b-faller/metamusic#2]
Hi there,
Thank you for making this! This has been extremely helpful for a project I'm working on. The project is nearly complete, however, I can't seem to locate any data from this JSON (below line) regarding the record label, which is visible on any Apple Music album:
https://github.com/b-faller/metamusic/blob/c0f3cd497e314e097469416f2ca77f99dde62247/main.py#L152

\
Example of record label on Apple Music album:
<img width="1160" alt="Screen Shot 2023-03-20 at 5 58 48 PM" src="https://user-images.githubusercontent.com/31714622/226496321-a0aa86e9-6119-46f9-8830-8ebf8035521f.png">

Is there any way I can get this data? This is the last piece I need for my project :) Any help would be greatly appreciated.

Thanks,
Nicolas

**Comment by nicolasespinoza** [comment]
Nevermind!

I asked ChatGPT to figure this out, and got the following code which can be used in main.py (and works flawlessly):
```
def get_record_label(soup) -> str:
    tracklist_footer_description: list[str] = soup.find('p', attrs={'data-testid': 'tracklist-footer-description'})\
        .text.split("\n")
    return tracklist_footer_description[2]
```

Thanks again for this awesome repo! Cheers 🍻

**Comment by b-faller** [comment]
You're welcome! 🙂
